In [4]:
#Basic information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  str
 2   Order Date      51290 non-null  datetime64[us]
 3   Ship Date       51290 non-null  datetime64[us]
 4   Ship Mode       51290 non-null  str
 5   Customer ID     51290 non-null  str
 6   Customer Name   51290 non-null  str
 7   Segment         51290 non-null  str
 8   Postal Code     9994 non-null   float64
 9   City            51290 non-null  str
 10  State           51290 non-null  str
 11  Country         51290 non-null  str
 12  Region          51290 non-null  str
 13  Market          51290 non-null  str
 14  Product ID      51290 non-null  str
 15  Category        51290 non-null  str
 16  Sub-Category    51290 non-null  str
 17  Product Name    51290 non-null  str
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  str
dtypes: datetime64[us](2), float64(5), int64(2), str(15)
memory usage: 9.4 MB

In [2]:
import pandas as pd
df = pd.read_excel("global_superstore_2016.xlsx")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.77,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [5]:
#Number of rows and coolumns
df.shape

(51290, 24)

In [6]:
#Summary statistics
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit,Shipping Cost
count,51290.00000,51290,51290,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.50000,2014-05-11 21:26:49.155780,2014-05-15 20:42:42.745174,55190.379428,246.490581,3.476545,0.142908,28.610982,26.478567
min,1.00000,2012-01-01 00:00:00,2012-01-03 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000,1.002000
25%,12823.25000,2013-06-19 00:00:00,2013-06-23 00:00:00,23223.000000,30.758625,2.000000,0.000000,0.000000,2.610000
50%,25645.50000,2014-07-08 00:00:00,2014-07-12 00:00:00,56430.500000,85.053000,3.000000,0.000000,9.240000,7.790000
75%,38467.75000,2015-05-22 00:00:00,2015-05-26 00:00:00,90008.000000,251.053200,5.000000,0.200000,36.810000,24.450000
max,51290.00000,2015-12-31 00:00:00,2016-01-07 00:00:00,99301.000000,22638.480000,14.000000,0.850000,8399.976000,933.570000
std,14806.29199,NaN,NaN,32063.693350,487.565361,2.278766,0.212280,174.340972,57.251373

In [7]:
#Check missing values
df.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
Postal Code       41296
City                  0
State                 0
Country               0
Region                0
Market                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df = df.drop_duplicates()
print("Duplicates removed")
print("New dataset shape:",df.shape)

Duplicates removed
New dataset shape: (51290, 24)

In [14]:
# Total revenue by category
category_revenue = df.groupby("Category")["Sales"].sum()

category_revenue

Category
Furniture          4.110452e+06
Office Supplies    3.787493e+06
Technology         4.744557e+06
Name: Sales, dtype: float64

In [15]:
# Sort data by Category and Sales
sorted_data = df.sort_values(
    by=["Category", "Sales"],
    ascending=[True, False]
)

sorted_data.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
1156,28242,ID-2013-SC203057-41488,2013-08-02,2013-08-08,Standard Class,SC-203057,Sean Christensen,Consumer,NaN,Adelaide,...,FUR-CH-4655,Furniture,Chairs,"Hon Executive Leather Armchair, Black",5759.964,14,0.1,-0.336,187.19,Medium
80,13879,ES-2015-HG1484545-42327,2015-11-19,2015-11-23,Standard Class,HG-1484545,Harry Greene,Consumer,NaN,Lille,...,FUR-CH-4654,Furniture,Chairs,"Hon Executive Leather Armchair, Adjustable",5729.346,14,0.1,63.546,572.95,High
42,25795,IN-2015-VG2180558-42273,2015-09-26,2015-09-28,Second Class,VG-2180558,Vivek Grady,Corporate,NaN,Thiruvananthapuram,...,FUR-BO-5951,Furniture,Bookcases,"Sauder Classic Bookcase, Traditional",5667.870,13,0.0,2097.030,658.35,Medium
334,21263,IN-2015-MB173057-42179,2015-06-24,2015-06-28,Standard Class,MB-173057,Maria Bertelson,Consumer,NaN,Sydney,...,FUR-BO-5948,Furniture,Bookcases,"Sauder Classic Bookcase, Metal",5486.670,14,0.1,2316.510,346.60,Medium
192,15359,ES-2014-JG15160139-41660,2014-01-21,2014-01-24,Second Class,JG-15160139,James Galang,Consumer,NaN,Stockton-on-Tees,...,FUR-TA-3344,Furniture,Tables,"Barricks Conference Table, Fully Assembled",5451.300,6,0.0,2071.440,432.13,Medium
402,28557,IN-2013-BT1153058-41331,2013-02-26,2013-03-04,Standard Class,BT-1153058,Bradley Talbott,Home Office,NaN,Muzaffarpur,...,FUR-TA-3344,Furniture,Tables,"Barricks Conference Table, Fully Assembled",5451.300,6,0.0,327.060,320.27,Medium
7,31192,IN-2013-MB1808592-41378,2013-04-14,2013-04-18,Standard Class,MB-1808592,Mick Brown,Consumer,NaN,Hamilton,...,FUR-TA-3764,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.840,6,0.0,996.480,878.38,High
64,25314,IN-2015-DB1340527-42022,2015-01-18,2015-01-23,Standard Class,DB-1340527,Denny Blanton,Consumer,NaN,Wuxi,...,FUR-CH-5774,Furniture,Chairs,"SAFCO Executive Leather Armchair, Black",5049.000,11,0.0,656.370,595.50,High
11,28879,ID-2013-AJ107801-41383,2013-04-19,2013-04-22,First Class,AJ-107801,Anthony Jacobs,Corporate,NaN,Kabul,...,FUR-TA-3420,Furniture,Tables,"Bevis Conference Table, Fully Assembled",4626.150,5,0.0,647.550,835.57,High
118,14070,IT-2012-ON1871545-40955,2012-02-16,2012-02-19,Second Class,ON-1871545,Odella Nelson,Corporate,NaN,Muret,...,FUR-CH-5774,Furniture,Chairs,"SAFCO Executive Leather Armchair, Black",4544.100,11,0.1,1868.130,506.27,Medium

In [16]:
# Correlation matrix for numerical columns
correlation_matrix = df.corr(numeric_only=True)

correlation_matrix

,Row ID,Postal Code,Sales,Quantity,Discount,Profit,Shipping Cost
Row ID,1.000000,0.009671,-0.043889,-0.173483,0.087594,-0.019037,-0.038431
Postal Code,0.009671,1.000000,-0.023854,0.012761,0.058443,-0.029961,-0.025491
Sales,-0.043889,-0.023854,1.000000,0.313577,-0.086722,0.484918,0.767835
Quantity,-0.173483,0.012761,0.313577,1.000000,-0.019875,0.104365,0.271804
Discount,0.087594,0.058443,-0.086722,-0.019875,1.000000,-0.316490,-0.078153
Profit,-0.019037,-0.029961,0.484918,0.104365,-0.316490,1.000000,0.354423
Shipping Cost,-0.038431,-0.025491,0.767835,0.271804,-0.078153,0.354423,1.000000